// NotifyAnims.h — the one registry every notification animation goes through.
//
// Two kinds of entry live in the same table and the renderer cannot tell them
// apart:
//
//   pixel       a frame set from notify_frames.h, which is GENERATED by
//               tools/extract_notify.py. That header is never hand-edited, so
//               this file wraps it rather than growing it.
//   procedural  a function returning the colour of one pixel. Costs no flash
//               beyond its own code, which is what makes a new type cheap: the
//               accent colour is passed in, so one shape serves every colour a
//               preset or an API override asks for.
//
// Why a per-pixel function and not a draw routine using fillCircle and friends:
// the panel has no framebuffer, so a routine that clears its box and then draws
// into it puts a fully black box on screen for the milliseconds the drawing
// takes, every frame. That reads as heavy flicker. Returning one pixel at a time
// lets the renderer write each pixel exactly once per frame, in place, which is
// what the pixel animations have always done and why they do not flicker.
//
// Adding an animation is one table row here plus, for a procedural one, the
// pixel function above it. Nothing else in the feature needs to know.
#pragma once
#include <stdint.h>
#include "notify_frames.h"

class Arduino_GFX;

// What a procedural animation is told about the frame it is painting. The box is
// `w` x `h` panel pixels; `u` is one grid unit, so a shape written in units of
// `u` keeps its proportions on every board and band layout.
typedef struct {
  int      w, h;
  int      u;
  uint16_t frame;
  uint16_t accent;   // already tinted; the colour the request or preset asked for
  uint16_t bg;       // pre-tinted black, so a pixel function never calls gfxTint
} NotifyPixelCtx;

// Colour of the pixel at (x, y) within the box, 0 <= x < c.w, 0 <= y < c.h.
// Return c.bg for background. Called once per pixel per frame, so keep it to
// integer arithmetic — no sqrt, no floating point.
typedef uint16_t (*NotifyAnimPixel)(int x, int y, const NotifyPixelCtx& c);

typedef struct {
  const char*       name;        // what the API's "anim" field matches on
  const NotifyAnim* pixels;      // pixel entry from notify_frames.h, else NULL
  NotifyAnimPixel   pixel;       // procedural renderer, else NULL
  // Procedural entries only: box in grid units, frame count, hold per frame. A
  // pixel entry carries its own in the generated table and leaves these zero,
  // so nothing here can drift out of step with a regenerated notify_frames.h.
  uint8_t           procW, procH;
  uint16_t          procFrames;
  uint16_t          procPeriodMs;
} NotifyAnimEntry;

// Row numbers in notify_anim_table, used by NotifyTypes.h and the queue.
//
// These are NOT the NOTIFY_ANIM_DONE / NOTIFY_ANIM_WAITING that notify_frames.h
// defines: those index the generated notify_anims[] frame sets, a different and
// much shorter array. Both spaces happen to start 0, 1 with the same two
// animations today, which is exactly the kind of coincidence that stops being
// true the moment either table gains a row — hence the separate prefix.
enum NotifyAnimId {
  NOTIFY_ANIM_ID_JUMPING = 0,
  NOTIFY_ANIM_ID_WAVING,
  NOTIFY_ANIM_ID_INFO,
  NOTIFY_ANIM_ID_WARN,
  NOTIFY_ANIM_ID_BANG,
  NOTIFY_ANIM_ID_PULSE,
  NOTIFY_ANIM_ID_COUNT,
};

extern const NotifyAnimEntry notify_anim_table[NOTIFY_ANIM_ID_COUNT];

// Resolve an API "anim" name to a table index, or -1 when it is unknown. The
// legacy names the endpoint shipped with ("done", "waiting") resolve too.
int notifyAnimFind(const char* name);

// The renderer reads every animation through these and never branches on kind.
uint8_t  notifyAnimW(const NotifyAnimEntry& e);
uint8_t  notifyAnimH(const NotifyAnimEntry& e);
uint16_t notifyAnimFrames(const NotifyAnimEntry& e);
uint16_t notifyAnimHold(const NotifyAnimEntry& e, uint16_t frame);

// Paint one frame of a procedural animation, one row at a time out of a stack
// buffer. Each pixel in the box is written exactly once, so there is no blank
// intermediate state to flicker.
void notifyAnimRender(Arduino_GFX* gfx, const NotifyAnimEntry& e, int x0, int y0,
                      int cell, uint16_t frame, uint16_t accent);
